### ISSUE TITLE
What is the name of this package? What library to load in R?

### ISSUE THREAD

**Issue by NeginValizadegan** [antonioggsousa/micrUBIfuns#1]

**Comment by antonioggsousa** [comment]
Hi @NeginValizadegan, 

Thank you for your interest in the package. This is an experimental/under development R package to automatize some tasks that I personal do when I'm working with (mostly) metabarcoding/microbiome data. The package is not in any official R repository, such as CRAN or Bioconductor. 

Answering to your question, the name of the package is `micrUBIfuns` because it contains functions (**funs** - suffix) to work with microbiome data (**micr** - prefix). **UBI** is a reference to the place where I work, Bioinformatics Unit (aka UBI) at IGC. 

Since the package is not available in the official repositories you can not install it through the more *traditional* channels. Though you can install it directly from this GitHub repository with the help of the package `devtools` ([see the docs](https://www.rdocumentation.org/packages/devtools/versions/2.4.1)). 

Assuming that you've the R package `devtools` installed in your R environment (you can attempt to install it by doing `install.packages("devtools")`), to install the `micrUBIfuns` R package, you need to do: 

`devtools::install_github("antonioggsousa/micrUBIfuns")`

Then to load the `micrUBIfuns` R package, do: 

`library("micrUBIfuns")`

Please let me know if you were able to install the package successfully.
